data_paths:
    cases: https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities-time.csv
    sus: treated_covid19_SUS_database.csv

models:
    - sir

model_parameters:
    sir:
        sick_days: 15
        i2_percentage: 15
        i3_percentage: 5
        days_from_t0: 365


scenarios:
    nothing: 
        R0:
            lower_bound: 2.5
            upper_bound: 3.2
    isolation: 
        R0: 
            lower_bound: 1.2
            upper_bound: 2.4
    lockdown:
        R0:
            lower_bound: 1.1
            upper_bound: 1.5