get_data_paths:
    cases_covid19br: https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities-time.csv
    cases_brasilio: https://brasil.io/api/dataset/covid19/caso/data?format=json
  
raw_paths:
    cases_covid19br: city_cases_covid19br.csv
    cases_brasilio: city_cases_brasilio.csv
    sus: covid19_SUS_database.csv
    
treated_paths:
    cases_covid19br: last_cases_covid19br.csv
    cases_brasilio: last_cases_covid19br.csv
    sus: treated_covid19_SUS_database.csv

models:
    - sir
    - seir

model_parameters:
    sir:
        sick_days: 15
        i2_percentage: 15
        i3_percentage: 5
        days_from_t0: 365
    seir:
        sick_days: 15
        i2_percentage: 15
        i3_percentage: 5
        days_from_t0: 365
        sigma: 0.5

scenarios:
    nothing: 
        R0:
            lower_bound: 2.5
            upper_bound: 3.2
    isolation: 
        R0: 
            lower_bound: 1.2
            upper_bound: 2.4
    lockdown:
        R0:
            lower_bound: 1.1
            upper_bound: 1.5